name: learn_github_workshop
on: [push, workflow_dispatch]
jobs:
  if_job: #podmínka
    if: ${{ github.triggering_actor == 'TesenaJJ' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo_name_podminka
        run: echo triggnula me "${{ github.triggering_actor}}"
    
  ahoj_svete:
    runs-on: ubuntu-latest
    steps:
        - name: ahoj_svete
          run: echo Hello world
          
          
  # druhý job 
  need_job:
    needs: ahoj_svete # závislý na ahoj_svete, tj. spusti se az po nem      
    runs-on: ubuntu-latest
    steps:
      - name: need_2echa
        run: |
          echo Ahoj,
          echo ja se spustim az dobehne job ahoj svete
          
  secret_var_job:
    runs-on: ubuntu-latest
    env: 
      PROMENNA: oblibeny_hrdina
      VAR: $SECRETE_DONT_READ
    steps:
      - name: ukazka_promenne
        run: |
          echo $PROMENNA
          echo $VAR
        
  zavislak:
    runs-on: ubuntu-latest
    needs: [if_job, ahoj_svete, need_job, secret_var_job]
    steps:
        - name: Zase_Prace
          run: |
            echo Tak ja teda jdu
            echo "${{ toJSON(needs) }}"
          
